name: imgix_core_dart
description: Imgix package for Dart.
version: 1.0.0+1
homepage: https://github.com/Nikkei/imgix_core_dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
