name: imgix_core_dart
description: Imgix package for flutter.
version: 1.0.0-nullsafety.0
homepage: https://sudame.net

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  crypto: ^3.0.0
  meta: ^1.3.0

dev_dependencies:
  test: ^1.16.8
